"""implement partial index in booking table

Revision ID: 4c3882ea4539
Revises: 433235dbe836
Create Date: 2026-09-02 12:36:28.234386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3882ea4539'
down_revision: Union[str, Sequence[str], None] = '433235dbe836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_booking_event_seat'), 'bookings', type_='unique')
    op.create_index('uq_active_event_seat', 'bookings', ['event_id', 'seat_id'], unique=True, postgresql_where=sa.text("status = 'CONFIRMED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_event_seat', table_name='bookings', postgresql_where=sa.text("status = 'CONFIRMED'"))
    op.create_unique_constraint(op.f('uq_booking_event_seat'), 'bookings', ['event_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
