"""fix cascade issue in seat.py

Revision ID: ad190c6aeaa0
Revises: b2090919035f
Create Date: 2026-08-20 20:48:25.033795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad190c6aeaa0'
down_revision: Union[str, Sequence[str], None] = 'b2090919035f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('seats_event_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_event_id_fkey'), 'seats', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
