"""rename organizer_id to organiser_id

Revision ID: daac1e5c6da0
Revises: 47dd830f2c8c
Create Date: 2026-08-18 18:28:51.080539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daac1e5c6da0'
down_revision: Union[str, Sequence[str], None] = '47dd830f2c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organiser_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(op.f('events_organizer_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['organiser_id'], ['id'])
    op.drop_column('events', 'organizer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_organizer_id_fkey'), 'events', 'users', ['organizer_id'], ['id'])
    op.drop_column('events', 'organiser_id')
    # ### end Alembic commands ###
